name: docs
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install .[dev] && sphinx-build -W docs html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'html'
      - id: deployment
        uses: actions/deploy-pages@v4
