name: nanopy
on: [push]

jobs:
  common:
    runs-on: ubuntu-latest, macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -Ur requirements.txt
      - run: python setup.py build_ext -i
      - run: python travis.py
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -Ur requirements.txt
      - run: USE_VC=1 python setup.py build_ext -i
      - run: python travis.py

