on: [push, pull_request]
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - run: pipx run build -s
    - run: pip install -ve .[dev]
    - run: coverage run -m unittest
    - run: coverage report
    - run: black --check *.py */*.py */*/*.py nanopy-wallet
    - run: isort -c .
    - run: clang-format --dry-run -Werror src/nanopy/ext.c
    - run: mypy
    - run: pylint --extension-pkg-allow-list=nanopy.ext src
    - run: sphinx-build -W docs _site
    - run: sudo apt update
    - run: sudo apt install libomp-dev ocl-icd-opencl-dev pocl-opencl-icd clinfo
    - run: CC=clang pip install -ve .
    - run: python -m unittest
    - run: clinfo
    - run: USE_OCL=1 pip install -ve .
    - run: python -m unittest
    - uses: actions/upload-artifact@v7
      with:
        name: dist
        path: dist
    - uses: actions/upload-pages-artifact@v4
  platforms:
    needs: base
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-26, macos-26-intel, windows-latest, windows-11-arm]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: 3.x
    - run: pip install mnemonic
    - if: runner.os != 'macOS'
      run: pip install -ve .
    - if: runner.os == 'macOS'
      run: CC=gcc-15 pip install -ve .
    - run: python -m unittest
  versions:
    needs: base
    strategy:
      matrix:
        py: ['3.14.x', '3.13.x', '3.12.x', '3.11.x', '3.10.x']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.py }}
    - run: pip install mnemonic
    - run: pip install -ve .
    - run: python -m unittest
  deploy:
    if: github.ref_type == 'tag'
    needs: [platforms, versions]
    permissions:
      pages: write
      id-token: write
    environment: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v8
      with:
        name: dist
        path: dist
    - uses: pypa/gh-action-pypi-publish@release/v1
    - uses: actions/deploy-pages@v4
