name: nanopy
on: [push]

jobs:
  common:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -Ur requirements.txt
      - if: runner.os != 'Windows'
        run: python setup.py build_ext -i
      - if: runner.os == 'Windows'
        run: python setup.py build_ext -i
        env:
          USE_VC: 1
      - run: python travis.py

