name: nanopy
on: [push]

jobs:
  common:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        pu: [cpu]
        include:
          - arch: gpu
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -Ur requirements.txt
      - if: runner.os != 'Windows' && runner.pu == 'cpu'
        run: python setup.py build_ext -i
      - if: runner.os == 'Windows'
        run: python setup.py build_ext -i
        env:
          USE_VC: 1
      - if: runner.os == 'Linux' && runner.pu == 'gpu'
        run: |
          sudo apt-get update
          sudo apt-get install ocl-icd-opencl-dev intel-opencl-icd clinfo
          python setup.py build_ext -i
          clinfo
        env:
          USE_GPU: 1
      - if: runner.pu == 'cpu'
        run: python travis.py

