name: nanopy
on: [push]

jobs:
  aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: aarch64
          distro: ubuntu20.04
          install: |
            apt-get update -q -y
            apt-get install -q -y g++ python3-dev python3-pip
          run: |
            pip3 install -Ur requirements.txt
            python3 setup.py build_ext -i
            python3 travis.py

