on: [push, pull_request]
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: pipx run build -s
    - run: pip install -ve .[dev]
    - run: black --check .
    - run: isort -c .
    - run: clang-format --dry-run -Werror src/nanopy/ext.c
    - run: mypy
    - run: pylint --extension-pkg-allow-list=nanopy.ext src tests
    - run: coverage run -m unittest
    - run: coverage report
    - run: sphinx-build -W docs _site
    - run: sudo apt update
    - run: sudo apt install bear clinfo libomp-dev ocl-icd-opencl-dev pocl-opencl-icd
    - run: CC=clang bear -- pip install -ve .
    - run: clang-tidy src/nanopy/ext.c
    - run: python -m unittest
    - run: USE_OMP=1 bear -- pip install -ve .
    - run: clang-tidy src/nanopy/ext.c
    - run: python -m unittest
    - run: clinfo
    - run: USE_OCL=1 bear -- pip install -ve .
    - run: clang-tidy src/nanopy/ext.c
    - run: python -m unittest
    - uses: actions/upload-artifact@v7
      with:
        name: nanopy-sdist
        path: dist
    - uses: actions/upload-pages-artifact@v5
  wheels:
    needs: base
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-26, macos-26-intel, windows-latest, windows-11-arm]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - run: pipx run cibuildwheel
    - uses: actions/upload-artifact@v7
      with:
        name: nanopy-${{ matrix.os }}
        path: wheelhouse/*.whl
  deploy:
    if: github.ref_type == 'tag'
    needs: wheels
    permissions:
      pages: write
      id-token: write
    environment: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v8
      with:
        pattern: nanopy-*
        path: dist
        merge-multiple: true
    - uses: pypa/gh-action-pypi-publish@release/v1
    - uses: actions/deploy-pages@v4
