name: nanopy
on: [push]

jobs:
  common:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      if: runner.os == 'Windows'
      USE_VC: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -Ur requirements.txt
      - run: python setup.py build_ext -i
      - run: python travis.py

