name: nanopy
on: [push]

jobs:
  common:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [amd64]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - arch: aarch64
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - if: ${{ matrix.arch=="aarch64" }}
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
      - uses: actions/setup-python@v2
      - run: pip install -Ur requirements.txt
      - if: runner.os != 'Windows'
        run: python setup.py build_ext -i
      - if: runner.os == 'Windows'
        run: python setup.py build_ext -i
        env:
          USE_VC: 1
      - run: python travis.py

