name: nanopy
on:
  push:
    branches: ["main"]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-15-intel, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - if: runner.os == 'macOS'
        run: CC=gcc-15 pip install -e .[dev] && pytest
      - if: runner.os != 'macOS'
        run: pip install -e .[dev] && pytest
      - if: matrix.os == 'ubuntu-latest'
        run: |
          mypy && pylint nanopy && sphinx-build -W docs _site
          sudo apt update && sudo apt install ocl-icd-opencl-dev intel-opencl-icd
          rm -rf build && USE_GPU=1 pip install .[dev]
      - if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-pages-artifact@v4
      - if: matrix.os == 'ubuntu-latest'
        uses: actions/deploy-pages@v4
